const env = {
  APP_NAME: process.env.APP_NAME,
  NODE_ENV: process.env.NODE_ENV,
  PORT: process.env.PORT,
  SERVER_DOMAIN: process.env.SERVER_DOMAIN,
  CLIENT_DOMAIN: process.env.CLIENT_DOMAIN,
  BLUEBIRD_W_FORGOTTEN_RETURN: process.env.BLUEBIRD_W_FORGOTTEN_RETURN,
};

const secret = {
  JWT_SECRET_KEY: process.env.JWT_SECRET_KEY,
  ALLOWED_CSRF: process.env.ALLOWED_CSRF,
  CSRF_SECRET: process.env.CSRF_SECRET,
  SESSION_SECRET: process.env.SESSION_SECRET,
  SESSION_TTL: process.env.SESSION_TTL,
};

const oAuth = {
  KAKAO_JS_APP_KEY: process.env.KAKAO_JS_APP_KEY,
  KAKAO_CLIENT_SECRET: process.env.KAKAO_CLIENT_SECRET,
  NAVER_CLIENT_ID: process.env.NAVER_CLIENT_ID,
  NAVER_CLIENT_SECRET: process.env.NAVER_CLIENT_SECRET,
};

const database = {
  DATABASE_DIALECT: process.env.DATABASE_DIALECT,
  MYSQL_USER: process.env.MYSQL_USER,
  MYSQL_PASSWORD: process.env.MYSQL_PASSWORD,
  MYSQL_DATABASE: process.env.MYSQL_DATABASE,
  MYSQL_ROOT_PASSWORD: process.env.MYSQL_ROOT_PASSWORD,
  MYSQL_HOST: process.env.MYSQL_HOST,
  MYSQL_PORT: process.env.MYSQL_PORT,
  MYSQL_TEST_USER: process.env.MYSQL_TEST_USER,
  MYSQL_TEST_PASSWORD: process.env.MYSQL_TEST_PASSWORD,
  MYSQL_TEST_DATABASE: process.env.MYSQL_TEST_DATABASE,
  MYSQL_TEST_ROOT_PASSWORD: process.env.MYSQL_TEST_ROOT_PASSWORD,
  MYSQL_TEST_HOST: process.env.MYSQL_TEST_HOST,
  MYSQL_TEST_PORT: process.env.MYSQL_TEST_PORT,
  MYSQL_PRODUCTION_USER: process.env.MYSQL_PRODUCTION_USER,
  MYSQL_PRODUCTION_PASSWORD: process.env.MYSQL_PRODUCTION_PASSWORD,
  MYSQL_PRODUCTION_DATABASE: process.env.MYSQL_PRODUCTION_DATABASE,
  MYSQL_PRODUCTION_ROOT_PASSWORD: process.env.MYSQL_PRODUCTION_ROOT_PASSWORD,
  MYSQL_PRODUCTION_HOST: process.env.MYSQL_PRODUCTION_HOST,
  MYSQL_PRODUCTION_PORT: process.env.MYSQL_PRODUCTION_PORT,
};

const email = {
  MAIL_USER: process.env.MAIL_USER,
  MAIL_PASSWORD: process.env.MAIL_PASSWORD,
  MAIL_DEV_USER: process.env.MAIL_DEV_USER,
  MAIL_DEV_PASSWORD: process.env.MAIL_DEV_PASSWORD,
};

const logger = {
  LOG_COLOR_ERROR: process.env.LOG_COLOR_ERROR,
  LOG_COLOR_WARN: process.env.LOG_COLOR_WARN,
  LOG_COLOR_INFO: process.env.LOG_COLOR_INFO,
  LOG_COLOR_SQL: process.env.LOG_COLOR_SQL,
  LOG_COLOR_SYSTEM: process.env.LOG_COLOR_SYSTEM,
  LOG_COLOR_DEBUG: process.env.LOG_COLOR_DEBUG,
  LOG_COLOR_SILLY: process.env.LOG_COLOR_SILLY,
  LOG_INFO_SAVED_UNTIL: process.env.LOG_INFO_SAVED_UNTIL,
  LOG_ERROR_SAVED_UNTIL: process.env.LOG_ERROR_SAVED_UNTIL,
  LOG_SYSTEM_SAVED_UNTIL: process.env.LOG_SYSTEM_SAVED_UNTIL,
};

module.exports = {
  env,
  secret,
  oAuth,
  database,
  email,
  logger,
};
